# Generated by Django 5.2.1 on 2025-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=10)),
                ("summary", models.TextField()),
                ("poster_url", models.URLField()),
            ],
        ),
    ]
