# Generated by Django 5.2.1 on 2025-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="app.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="app.director"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(default="Non indiqué", max_length=10),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(default="Non indiqué"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="producers",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="app.producer"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="summary",
            field=models.TextField(default="Non indiqué"),
        ),
    ]
