# Generated by Django 5.2.1 on 2025-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_movie_actors_alter_movie_directors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
    ]
